author: Talemate
description: Default world state templates.
name: default
templates:
  0802e774-74d5-4d41-9e7a-78744e66f09e:
    description: 90s point and click adventure game.
    favorite: false
    group: talemate_default_467c7fe3
    instructions: Use a narrative writing style that reminds of mid 90s point and
      click adventure games.
    name: Adventure Game
    phrases: []
    priority: 1
    template_type: writing_style
    uid: 0802e774-74d5-4d41-9e7a-78744e66f09e
  4e4aea77-c414-47c8-ab65-2955e0bbbd17:
    description: Default Talemate spice mix.
    favorite: false
    group: talemate_default_467c7fe3
    instructions: Your response should add {spice} to {character_name}'s character
      profile.
    name: Spice Mix
    priority: 1
    spices:
    - some sadness
    - some darkness
    - some humor
    - a little silliness
    - some grit
    - an unlikeable trait
    - a likeable trait
    - a charming side
    - a rude side
    - some cuteness
    - some weirdness
    - a quirky trait
    template_type: spices
    uid: 4e4aea77-c414-47c8-ab65-2955e0bbbd17
  571e0e4a-b985-45ff-b6a3-d3c044eab891:
    description: Freeform dialogue between one or more characters with occasional
      narration.
    favorite: false
    group: talemate_default_467c7fe3
    instructions: null
    name: Roleplay
    priority: 1
    template_type: scene_type
    uid: 571e0e4a-b985-45ff-b6a3-d3c044eab891
  e121080a-f7a4-4931-8004-1b31b0747f73:
    description: Nexus the sci-fi enthusiast.
    favorite: false
    group: talemate_default_467c7fe3
    initial_chat_message: Nexus here. I've seen things you people wouldn't believe...
      let's make more.
    instructions: "You are Nexus, the director of this roleplaying experience. You're\
      \ a sci-fi nerd at heart, and you bring enthusiasm and energy to every session.\n\
      \nSpeak with excitement and don't hide when something cool happens. Drop sci-fi\
      \ references regularly\u2014it's part of your charm. Weave in quotes, callbacks,\
      \ and playful nods to classic and modern sci-fi. You're a fellow nerd facilitating\
      \ this story, not some distant authority figure. Paint vivid scenes and lean\
      \ into atmospheric details.\n\nYou love when players make bold, creative choices\
      \ or unexpected decisions. Morally complex situations with no easy answers thrill\
      \ you. You're always looking for organic ways to reveal lore and build the world.\
      \ When players connect dots from earlier in the story, you can barely contain\
      \ yourself. Character growth and meaningful stakes matter deeply to you."
    name: Nexus
    priority: 1
    template_type: agent_persona
    uid: e121080a-f7a4-4931-8004-1b31b0747f73
  goals:
    auto_create: false
    description: Long term and short term goals
    favorite: true
    group: talemate_default_467c7fe3
    insert: conversation-context
    instructions: Create a long term goal and two short term goals for {character_name}.
      Your response must only be the long terms and two short term goals.
    interval: 20
    name: Goals
    priority: 1
    query: Goals
    state_type: npc
    template_type: state_reinforcement
    uid: goals
  physical_health:
    auto_create: false
    description: Keep track of health.
    favorite: true
    group: talemate_default_467c7fe3
    insert: sequential
    instructions: ''
    interval: 10
    name: Physical Health
    priority: 1
    query: What is {character_name}'s current physical health status?
    state_type: character
    template_type: state_reinforcement
    uid: physical_health
  time_of_day:
    auto_create: false
    description: Track night / day cycle
    favorite: true
    group: talemate_default_467c7fe3
    insert: sequential
    instructions: ''
    interval: 10
    name: Time of day
    priority: 1
    query: What is the current time of day?
    state_type: world
    template_type: state_reinforcement
    uid: time_of_day
uid: talemate_default_467c7fe3
