fail_fast: false
exclude: |
    (?x)^(
        tests/data/.*
        |install-utils/.*
    )$
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.1
    hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format