# Use an official node runtime as a parent image
FROM node:20

# Set the working directory in the container
WORKDIR /app

# Copy the frontend directory contents into the container at /app
COPY ./talemate_frontend /app

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Run frontend server
CMD ["npm", "run", "serve"]