"""
Node glossary generator.

Renders a markdown reference page set covering every registered node type
(Python node classes and dynamically imported JSON module graphs) into
``docs/user-guide/node-editor/reference/nodes/``.

Each page covers one category of nodes (see ``PREFIX_MAP`` /
``MODULE_MAP``). Everything above the ``GENERATED_MARKER`` line in a page
is hand-written and preserved across regenerations; everything below it is
owned by this generator and rewritten on every ``--write`` run.

Node metadata is read the same way ``writer.py`` reads it: by
instantiating each registered class once. ``PropertyField`` attributes are
accessed directly instead of via ``model_dump()`` so user-supplied
``generate_choices`` callables (which may touch runtime-only state) are
never invoked.
"""

from __future__ import annotations

import dataclasses
import re
from pathlib import Path

import structlog

from talemate.path import TALEMATE_ROOT, relative_to_root

log = structlog.get_logger("talemate.game.engine.nodes.tools.glossary")

__all__ = [
    "DEFAULT_DOCS_ROOT",
    "GENERATED_MARKER",
    "collect_node_docs",
    "render_pages",
    "write_pages",
    "check_pages",
]

DEFAULT_DOCS_ROOT = (
    TALEMATE_ROOT / "docs" / "user-guide" / "node-editor" / "reference" / "nodes"
)

GENERATED_MARKER = (
    "<!-- glossary:generated - everything below this line is generated by "
    "`python -m talemate.game.engine.nodes.tools glossary --write` - do not edit -->"
)

# Soft budget per page: the help agent's read_doc truncates at 15000
# characters, so a page that exceeds this renders a warning.
PAGE_SIZE_BUDGET = 14000

# Property default values longer than this are truncated in the tables.
MAX_DEFAULT_LENGTH = 160

# Registry prefix (longest match wins, matched against the registry path
# minus the node name) -> page slug. Prefixes not listed fall back to
# MODULE_MAP, then to their first path segment.
PREFIX_MAP: dict[str, str] = {
    # engine
    "assets": "assets",
    "context_id": "context-id",
    "data": "data",
    "data/number": "data-number",
    "data/string": "data-string",
    "event": "event",
    "focal": "focal",
    "input": "input",
    "package/talemate": "util-packaging",
    "prompt": "prompt",
    "raise": "raise",
    "response": "response",
    "scene/event/trigger": "scene",
    "scene/history": "scene-history",
    "scene/intention": "scene-intent",
    "scene/message": "scene-messages",
    "scene/worldstate": "scene-world-state",
    "state": "state",
    "util": "util",
    "util/packaging": "util-packaging",
    "ux": "ux",
    "validation": "validation",
    "websocket": "websocket",
    "websocket/signals": "websocket",
    # agents
    "agents": "agents",
    "agents/conversation": "agents-conversation",
    "agents/creator": "agents-creator",
    "agents/director": "agents-director",
    "agents/director/auto-direct": "agents-director-auto",
    "agents/director/events": "agents-director",
    "agents/director/fn": "agents-director",
    "agents/director/gameplay": "agents-director",
    "agents/director/chat": "agents-director-chat",
    "agents/director/plan": "agents-director-plan",
    "agents/editor": "agents-editor",
    "agents/memory": "agents-memory",
    "agents/narrator": "agents-narrator",
    "agents/summarize": "agents-summarizer",
    "agents/summarizer": "agents-summarizer",
    "agents/tts": "agents-tts",
    "agents/visual": "agents-visual",
    "agents/world_state": "agents-world-state",
}

# For flat registry prefixes shared by several source modules (the flat
# ``core/*`` space is populated by core, logic and run), the defining
# python module (last dotted segment) refines the page. Never consulted
# for dynamically imported JSON modules - their defining module is always
# ``core``.
MODULE_MAP: dict[str, str] = {
    "core": "core",
    "logic": "core-logic",
    "run": "core-functions",
    "api": "core-functions",
    "scene": "scene",
}

# Explicit per-registry overrides, applied before everything else.
NODE_OVERRIDES: dict[str, str] = {
    # asset meta / selection-context nodes are heavyweight - they get
    # their own page separate from the asset CRUD nodes
    "assets/MakeAssetAttachmentContext": "assets-meta",
    "assets/MakeAssetMeta": "assets-meta",
    "assets/SearchAssets": "assets-meta",
    "assets/SelectAssets": "assets-meta",
    "assets/UnpackAssetMeta": "assets-meta",
    "assets/UnpackAssetSelectionContext": "assets-meta",
    # pairs with the Dict Collector
    "data/MakeKeyValuePair": "data-collections",
    # registered under prompt/ but users look for it next to Advanced
    # Format on the string page - the two share their dynamic-input
    # variable semantics
    "prompt/Jinja2Format": "data-string",
    # visual agent: generation/backend nodes split off the prompt-building
    # page
    "agents/visual/AnalyzeImages": "agents-visual-generation",
    "agents/visual/BackendStatus": "agents-visual-generation",
    "agents/visual/GenerateImage": "agents-visual-generation",
    "agents/visual/GenerationRequest": "agents-visual-generation",
    "agents/visual/SelectBackend": "agents-visual-generation",
    "agents/visual/UnpackGenerationRequest": "agents-visual-generation",
    "agents/visual/UnpackGenerationResponse": "agents-visual-generation",
}

# slug -> (page title, one-line description used in the index table and as
# the default intro for newly created pages).
PAGE_TITLES: dict[str, tuple[str, str]] = {
    "index": (
        "Node Reference",
        "Complete reference of every node available in the node editor.",
    ),
    "agents": (
        "Agent Nodes",
        "Generic agent interaction: get an agent, call agent functions, read and count agent state variables.",
    ),
    "agents-conversation": (
        "Conversation Agent Nodes",
        "Generate character dialogue through the conversation agent.",
    ),
    "agents-creator": (
        "Creator Agent Nodes",
        "Contextual content generation: character attributes, dialogue instructions, content context and thematic lists.",
    ),
    "agents-director": (
        "Director Agent Nodes",
        "Director operations: scene direction, character persistence, voice assignment, dice rolls, narrator/actor direction functions and websocket handlers.",
    ),
    "agents-director-auto": (
        "Director Auto-Direction Nodes",
        "Automatic scene direction: candidates, scene intent, instruction cadence and auto-direction generation.",
    ),
    "agents-director-chat": (
        "Director Chat Nodes",
        "Director chat plumbing: chat context, action arguments, confirmation and sub-actions, plus context/query modules.",
    ),
    "agents-director-chat-actions": (
        "Director Chat Actions",
        "The director chat's action modules: direct the scene, update context/gamestate/story arc, create images, query, prompt or yield to the user.",
    ),
    "agents-director-chat-instructors": (
        "Director Chat Instructors",
        "The director chat's instructor modules: instruct characters, the narrator, world/history/story updates and character creation.",
    ),
    "agents-director-plan": (
        "Director Planning Nodes",
        "Director plans: create, update, advance and complete plans and their tasks.",
    ),
    "agents-editor": (
        "Editor Agent Nodes",
        "Clean up user input, narration and character messages through the editor agent.",
    ),
    "agents-memory": (
        "Memory Agent Nodes",
        "Query the long-term memory context database and unpack memory documents.",
    ),
    "agents-narrator": (
        "Narrator Agent Nodes",
        "Generate narration messages: progress, scene, environment, query, character entry/exit and time narration.",
    ),
    "agents-summarizer": (
        "Summarizer Agent Nodes",
        "Summarization: scene progression summaries, tag generation and message avatar hooks.",
    ),
    "agents-tts": (
        "Voice Agent Nodes",
        "Text-to-speech: get and unpack voices and generate speech through the voice agent.",
    ),
    "agents-visual": (
        "Visualizer Agent Prompt Nodes",
        "Visual prompt building: prompt parts, styles, finalization and unpacking.",
    ),
    "agents-visual-generation": (
        "Visualizer Agent Generation Nodes",
        "Visual generation: generation requests, image generation, backend selection/status and image analysis.",
    ),
    "agents-visual-modules": (
        "Visualizer Agent Modules",
        "Ready-made visual generation flows: generate visual assets, avatars, portraits, image edits and regenerations.",
    ),
    "agents-world-state": (
        "World State Agent Nodes",
        "World state operations: time advancement, character progression, world state emission and extraction.",
    ),
    "assets": (
        "Asset Nodes",
        "Scene asset CRUD: add, get, list, remove and update assets, cover and avatar images.",
    ),
    "assets-meta": (
        "Asset Meta And Selection Nodes",
        "Asset metadata, search, selection and attachment context for passing assets to generation.",
    ),
    "context-id": (
        "Context ID Nodes",
        "Context IDs: build, convert, compress, read and write context-addressable values and pins.",
    ),
    "core": (
        "Core Nodes",
        "Graph plumbing: module Input/Output/Property, Route, Watch, Null and Stage.",
    ),
    "core-functions": (
        "Function Nodes",
        "Callable node modules: define, get and call functions, for-each calls, returns, error handlers, breakpoints and scoped API functions.",
    ),
    "core-logic": (
        "Logic Nodes",
        "Branching and comparison: switches, routers, boolean logic and conditional routing.",
    ),
    "data": (
        "Data Nodes",
        "General value handling: get/set, conditionals, sorting, selection, UUIDs, JSON, object updates and length/capping helpers.",
    ),
    "data-collections": (
        "Dict And List Nodes",
        "Dictionaries and lists: make, get, set, update, pop, append, combine and collect.",
    ),
    "data-number": (
        "Number Nodes",
        "Numeric values: conversion, arithmetic, comparison and random numbers.",
    ),
    "data-string": (
        "String Nodes",
        "Strings: formatting, templates, joining, splitting, cleanup and excerpts.",
    ),
    "event": (
        "Event Nodes",
        "Emit agent/system/status messages and listen to scene events.",
    ),
    "focal": (
        "AI Function Nodes (Focal)",
        "AI function calling: define callable functions and arguments, unpack calls and collect results.",
    ),
    "input": (
        "Input Nodes",
        "Process and wait for player input in the scene loop.",
    ),
    "prompt": (
        "Prompt Nodes",
        "Build prompts and control generation: prompt construction, defaults and inference settings.",
    ),
    "raise": (
        "Flow Exception Nodes",
        "Stop graph execution or raise errors: Stop, input value errors and acted-as-character signals.",
    ),
    "response": (
        "Response Parsing Nodes",
        "Parse LLM responses: extractors for anchors, lists, movie-script dialogue and structured data.",
    ),
    "scene": (
        "Scene Nodes",
        "Scene lifecycle and metadata: title, description, introduction, content classification, scene loop and storyline modules.",
    ),
    "scene-characters": (
        "Scene Character Nodes",
        "Characters in the scene: get, make, activate/deactivate, remove and read/write attributes, details and descriptions.",
    ),
    "scene-history": (
        "Scene History Nodes",
        "Scene message history: query, summarize and manage archive entries and character activity.",
    ),
    "scene-intent": (
        "Scene Intent Nodes",
        "Scene intention: read and set the scene intent, scene phase and scene types.",
    ),
    "scene-messages": (
        "Scene Message Nodes",
        "Scene messages: create, version, hide and manipulate messages in the scene log.",
    ),
    "scene-world-state": (
        "World Entry Nodes",
        "World entries (get, save, unpack, remove) and generation options: spices and writing styles.",
    ),
    "state": (
        "State Nodes",
        "Graph state variables: get/set/unset across scopes (local, parent, shared, scene loop, game), counters and path variants.",
    ),
    "util": (
        "Utility Nodes",
        "Miscellaneous helpers: counters, diffs, list extraction, ISO date durations and module styling.",
    ),
    "util-packaging": (
        "Packaging Nodes",
        "Node module packaging: define, install and configure scene packages.",
    ),
    "ux": (
        "UX Nodes",
        "User-facing interface elements: choice elements, status displays and interactive prompts.",
    ),
    "validation": (
        "Validation Nodes",
        "Validate values: characters, asset IDs, context IDs, containment and set/unset checks.",
    ),
    "websocket": (
        "Websocket Nodes",
        "Websocket plumbing: routers, responses and operation done/failed signals.",
    ),
}


@dataclasses.dataclass
class SocketDoc:
    name: str
    type: str
    optional: bool = False
    description: str = ""


@dataclasses.dataclass
class PropertyDoc:
    name: str
    type: str
    default: str
    description: str
    choices: list | None = None
    dynamic_choices: bool = False
    min: float | int | None = None
    max: float | int | None = None
    step: float | int | None = None
    readonly: bool = False


@dataclasses.dataclass
class NodeDoc:
    registry: str
    title: str
    base_type: str
    module: str
    prose: str = ""
    inputs: list[SocketDoc] = dataclasses.field(default_factory=list)
    outputs: list[SocketDoc] = dataclasses.field(default_factory=list)
    properties: list[PropertyDoc] = dataclasses.field(default_factory=list)
    module_path: str = ""
    dynamic_imported: bool = False
    supports_dynamic_inputs: bool = False
    error: str = ""


_SECTION_RE = re.compile(r"(Inputs?|Outputs?|Properties):\s*$")
_BULLET_RE = re.compile(r"[-*]\s+`?([\w{}\[\]. ]+)`?\s*(?:\(([^)]*)\))?:\s*(.*)")

_SECTION_ALIASES = {
    "input": "inputs",
    "inputs": "inputs",
    "output": "outputs",
    "outputs": "outputs",
    "properties": "properties",
}


def _parse_docstring(docstring: str) -> tuple[str, dict[str, dict[str, str]]]:
    """
    Split a node docstring into prose and per-socket/property descriptions.

    Recognizes the ``Inputs:`` / ``Outputs:`` / ``Properties:`` bullet
    sections used across the node modules (``- name: description``).
    Everything else stays in the prose. Returns ``(prose, sections)``
    where ``sections`` maps section name -> {item name -> description}.
    """

    prose_lines: list[str] = []
    sections: dict[str, dict[str, str]] = {}
    current: dict[str, str] | None = None
    current_item: str | None = None

    for raw in (docstring or "").splitlines():
        line = raw.strip()

        header = _SECTION_RE.fullmatch(line)
        if header:
            current = sections.setdefault(_SECTION_ALIASES[header.group(1).lower()], {})
            current_item = None
            continue

        if current is None:
            prose_lines.append(line)
            continue

        if not line:
            current_item = None
            continue

        bullet = _BULLET_RE.fullmatch(line)
        if bullet:
            current_item = bullet.group(1).strip()
            desc = bullet.group(3).strip()
            qualifier = (bullet.group(2) or "").strip()
            if qualifier and qualifier.lower() not in ("optional",):
                desc = f"({qualifier}) {desc}" if desc else f"({qualifier})"
            current[current_item] = desc
            continue

        if current_item:
            # continuation line of the previous bullet
            current[current_item] = f"{current[current_item]} {line}".strip()
        else:
            # section ended with untagged text - back to prose
            current = None
            prose_lines.append(line)

    prose = "\n".join(prose_lines)
    # collapse 3+ consecutive newlines and trim
    prose = re.sub(r"\n{3,}", "\n\n", prose).strip()
    return prose, sections


def _fmt_value(value) -> str:
    from talemate.game.engine.nodes.core import UNRESOLVED

    if value is UNRESOLVED:
        return "unset"
    if value is None:
        return "None"
    if isinstance(value, str):
        formatted = f'"{value}"'
    else:
        formatted = repr(value)
    if len(formatted) > MAX_DEFAULT_LENGTH:
        formatted = formatted[:MAX_DEFAULT_LENGTH] + "…"
    return formatted


def _socket_type(socket_type) -> str:
    if isinstance(socket_type, (list, tuple)):
        return ", ".join(str(t) for t in socket_type)
    return str(socket_type)


def collect_node_docs() -> list[NodeDoc]:
    """Instantiate every registered node class and collect its metadata."""

    from .analysis import ensure_registry_loaded

    ensure_registry_loaded()

    from talemate.game.engine.nodes.core.dynamic import DynamicSocketNodeBase
    from talemate.game.engine.nodes.registry import NODES

    docs: list[NodeDoc] = []

    for registry, cls in sorted(NODES.items()):
        dynamic_imported = bool(getattr(cls, "__dynamic_imported__", False))
        prose, sections = _parse_docstring(cls.__doc__ or "")

        module_path = str(getattr(cls, "_module_path", "") or "")
        if module_path:
            try:
                module_path = str(relative_to_root(module_path))
            except ValueError:
                pass

        doc = NodeDoc(
            registry=registry,
            title=registry.split("/")[-1],
            base_type=getattr(cls, "_base_type", "") or "",
            module=cls.__module__,
            prose=prose,
            module_path=module_path,
            dynamic_imported=dynamic_imported,
            supports_dynamic_inputs=issubclass(cls, DynamicSocketNodeBase),
        )

        try:
            inst = cls()
        except Exception as exc:
            doc.error = f"{type(exc).__name__}: {exc}"
            log.warning(
                "glossary: could not instantiate node",
                registry=registry,
                error=doc.error,
            )
            docs.append(doc)
            continue

        doc.title = inst.title

        input_descs = sections.get("inputs", {})
        output_descs = sections.get("outputs", {})
        property_descs = sections.get("properties", {})

        doc.inputs = [
            SocketDoc(
                name=s.name,
                type=_socket_type(s.socket_type),
                optional=s.optional,
                description=input_descs.get(s.name, ""),
            )
            for s in inst.inputs
        ]
        doc.outputs = [
            SocketDoc(
                name=s.name,
                type=_socket_type(s.socket_type),
                description=output_descs.get(s.name, ""),
            )
            for s in inst.outputs
        ]

        try:
            field_definitions = inst.field_definitions
        except Exception as exc:
            field_definitions = {}
            log.warning(
                "glossary: could not read field definitions",
                registry=registry,
                error=str(exc),
            )

        for name, field in field_definitions.items():
            doc.properties.append(
                PropertyDoc(
                    name=name,
                    type=field.type,
                    default=_fmt_value(inst.properties.get(name, field.default)),
                    description=field.description or property_descs.get(name, ""),
                    choices=field.choices,
                    dynamic_choices=field.generate_choices is not None,
                    min=field.min,
                    max=field.max,
                    step=field.step,
                    readonly=field.readonly,
                )
            )

        docs.append(doc)

    return docs


def _page_slug(doc: NodeDoc) -> str:
    override = NODE_OVERRIDES.get(doc.registry)
    if override:
        return override

    parts = doc.registry.split("/")
    name = parts[-1]
    dirname = "/".join(parts[:-1])

    # the flat scene/* space is large; character manipulation nodes get
    # their own page
    if dirname == "scene" and "Character" in name:
        return "scene-characters"

    # dict/list container nodes split off the general data page
    if dirname == "data" and ("Dict" in name or "List" in name):
        return "data-collections"

    # director chat is the largest module family - split its action and
    # instructor modules off the chat plumbing page
    if parts[0] == "agents" and dirname.endswith("director/chat"):
        if name.startswith("directorAction"):
            return "agents-director-chat-actions"
        if name.startswith("instruct"):
            return "agents-director-chat-instructors"

    # visual agent: JSON module graphs get their own page next to the
    # python nodes
    if dirname == "agents/visual" and doc.dynamic_imported:
        return "agents-visual-modules"

    probe = dirname
    while probe:
        if probe in PREFIX_MAP:
            return PREFIX_MAP[probe]
        probe = probe.rsplit("/", 1)[0] if "/" in probe else ""

    if not doc.dynamic_imported:
        module_tail = doc.module.rsplit(".", 1)[-1]
        if module_tail in MODULE_MAP:
            return MODULE_MAP[module_tail]

    return parts[0]


def _page_title(slug: str) -> tuple[str, str]:
    if slug in PAGE_TITLES:
        return PAGE_TITLES[slug]
    title = slug.replace("-", " ").title() + " Nodes"
    return title, f"Reference for the `{slug}` node category."


def _escape_cell(text: str) -> str:
    return (text or "").replace("|", "\\|").replace("\n", " ").strip()


def _render_property_extras(prop: PropertyDoc) -> str:
    extras = []
    if prop.choices:
        shown = [f"`{c}`" for c in prop.choices[:12]]
        if len(prop.choices) > 12:
            shown.append("…")
        extras.append(f"Choices: {', '.join(shown)}.")
    elif prop.dynamic_choices:
        extras.append("Choices are generated at runtime.")
    if prop.min is not None and prop.max is not None:
        extras.append(f"Range: {prop.min} – {prop.max}.")
    elif prop.min is not None:
        extras.append(f"Min: {prop.min}.")
    elif prop.max is not None:
        extras.append(f"Max: {prop.max}.")
    if prop.readonly:
        extras.append("Read-only.")
    return " ".join(extras)


def _render_node(doc: NodeDoc, heading: str) -> str:
    out: list[str] = [f"## {heading}", ""]
    out.append(f"`{doc.registry}`")
    out.append("")

    if doc.error:
        out.append(
            f"_Metadata for this node could not be fully resolved "
            f"({_escape_cell(doc.error)})._"
        )
        out.append("")

    if doc.dynamic_imported:
        origin = f" defined in `{doc.module_path}`" if doc.module_path else ""
        out.append(f"Node module (base type `{doc.base_type}`){origin}.")
        out.append("")

    if doc.prose:
        out.append(doc.prose)
        out.append("")

    if doc.inputs:
        out.append("**Inputs**")
        out.append("")
        out.append("| Input | Type | Description |")
        out.append("| --- | --- | --- |")
        for socket in doc.inputs:
            desc = socket.description
            if socket.optional and "(optional)" not in desc.lower():
                desc = f"(optional) {desc}".strip()
            out.append(
                f"| `{socket.name}` | `{_escape_cell(socket.type)}` "
                f"| {_escape_cell(desc)} |"
            )
        out.append("")

    if doc.supports_dynamic_inputs:
        out.append(
            "This node supports **dynamic inputs** - additional input "
            "sockets can be added in the editor as needed, and connected "
            "values are collected with key inference (see "
            "[Collector Nodes](../../core-concepts/collector_nodes.md))."
        )
        out.append("")

    # agent Settings nodes mirror the agent's entire settings schema as
    # output sockets/properties; the per-agent documentation already
    # covers every field, so a pointer replaces the huge tables
    settings_node = doc.registry.startswith("agents/") and doc.registry.endswith(
        "/Settings"
    )

    if settings_node:
        agent_name = doc.registry.split("/")[1]
        out.append(
            f"Every setting of the {agent_name} agent is exposed as an "
            f"output socket named after the setting - see the agent's "
            f"documentation under [Agents](../../../agents/index.md) for "
            f"what each setting does."
        )
        out.append("")
    elif doc.outputs:
        out.append("**Outputs**")
        out.append("")
        out.append("| Output | Type | Description |")
        out.append("| --- | --- | --- |")
        for socket in doc.outputs:
            out.append(
                f"| `{socket.name}` | `{_escape_cell(socket.type)}` "
                f"| {_escape_cell(socket.description)} |"
            )
        out.append("")

    if doc.properties and not settings_node:
        out.append("**Properties**")
        out.append("")
        out.append("| Property | Type | Default | Description |")
        out.append("| --- | --- | --- | --- |")
        for prop in doc.properties:
            description = _escape_cell(prop.description)
            extras = _render_property_extras(prop)
            if description and extras and not description.endswith((".", "!", "?")):
                description += "."
            desc = " ".join(part for part in (description, extras) if part)
            out.append(
                f"| `{prop.name}` | `{_escape_cell(prop.type)}` "
                f"| `{_escape_cell(prop.default)}` | {desc} |"
            )
        out.append("")

    return "\n".join(out).rstrip() + "\n"


def render_pages(docs: list[NodeDoc]) -> dict[str, str]:
    """
    Render the generated portion of every glossary page.

    Returns a mapping of page slug -> generated markdown (the content that
    belongs below ``GENERATED_MARKER``). Includes the ``index`` page.
    """

    by_page: dict[str, list[NodeDoc]] = {}
    for doc in docs:
        by_page.setdefault(_page_slug(doc), []).append(doc)

    pages: dict[str, str] = {}

    for slug, page_docs in sorted(by_page.items()):
        page_docs.sort(key=lambda d: (d.registry.lower()))

        # disambiguate duplicate titles within a page so headings stay
        # unique anchors
        title_counts: dict[str, int] = {}
        for doc in page_docs:
            title_counts[doc.title] = title_counts.get(doc.title, 0) + 1
        headings = {
            doc.registry: (
                doc.title
                if title_counts[doc.title] == 1
                else f"{doc.title} (`{doc.registry}`)"
            )
            for doc in page_docs
        }

        out: list[str] = ["", ""]
        out.append(f"_{len(page_docs)} nodes._")
        out.append("")
        out.append("| Node | Registry path |")
        out.append("| --- | --- |")
        for doc in page_docs:
            anchor = re.sub(r"[^\w\s-]", "", headings[doc.registry].lower())
            anchor = re.sub(r"[-\s]+", "-", anchor.strip())
            out.append(f"| [{doc.title}](#{anchor}) | `{doc.registry}` |")
        out.append("")
        for doc in page_docs:
            out.append(_render_node(doc, headings[doc.registry]))

        pages[slug] = "\n".join(out).rstrip() + "\n"

    # index page: category overview table
    out = ["", ""]
    out.append(
        "Every node available in the node editor, grouped by category. "
        "Each page lists the node's registry path, inputs, outputs and "
        "properties."
    )
    out.append("")
    out.append("| Page | Nodes | Description |")
    out.append("| --- | --- | --- |")
    # sort by page title, not slug - slug order fronts all agents-* pages
    for slug, page_docs in sorted(
        by_page.items(), key=lambda item: _page_title(item[0])[0].lower()
    ):
        title, description = _page_title(slug)
        out.append(
            f"| [{title}]({slug}.md) | {len(page_docs)} | {_escape_cell(description)} |"
        )
    out.append("")
    pages["index"] = "\n".join(out).rstrip() + "\n"

    return pages


def _split_existing(content: str) -> tuple[str, str] | None:
    """Split page content into (intro, generated) at the marker line."""

    if GENERATED_MARKER not in content:
        return None
    intro, _, generated = content.partition(GENERATED_MARKER)
    return intro, generated


def _default_intro(slug: str) -> str:
    title, description = _page_title(slug)
    return f"# {title}\n\n{description}\n\n"


def _page_path(docs_root: Path, slug: str) -> Path:
    return docs_root / f"{slug}.md"


def write_pages(docs_root: Path | None = None) -> int:
    """Render and write all glossary pages. Returns an exit code."""

    docs_root = docs_root or DEFAULT_DOCS_ROOT
    docs_root.mkdir(parents=True, exist_ok=True)

    docs = collect_node_docs()
    pages = render_pages(docs)

    for slug, generated in pages.items():
        path = _page_path(docs_root, slug)
        intro = _default_intro(slug)
        if path.exists():
            split = _split_existing(path.read_text(encoding="utf-8"))
            if split is not None:
                intro = split[0]
            else:
                log.warning(
                    "glossary: page has no marker, restoring default intro",
                    page=str(path),
                )
        content = f"{intro}{GENERATED_MARKER}\n{generated}"
        path.write_text(content, encoding="utf-8")
        size = len(content)
        if size > PAGE_SIZE_BUDGET:
            log.warning(
                "glossary: page exceeds size budget",
                page=f"{slug}.md",
                size=size,
                budget=PAGE_SIZE_BUDGET,
            )

    for stale in sorted(docs_root.glob("*.md")):
        if stale.stem not in pages:
            log.warning("glossary: stale page not in render set", page=str(stale))

    print(f"glossary: wrote {len(pages)} pages to {docs_root}")
    return 0


def check_pages(docs_root: Path | None = None) -> int:
    """
    Verify the committed glossary pages match a fresh render.

    Returns 0 when in sync, 1 when pages are missing, stale or drifted.
    """

    docs_root = docs_root or DEFAULT_DOCS_ROOT

    docs = collect_node_docs()
    pages = render_pages(docs)

    problems: list[str] = []

    for slug, generated in sorted(pages.items()):
        path = _page_path(docs_root, slug)
        if not path.exists():
            problems.append(f"missing page: {path.name}")
            continue
        content = path.read_text(encoding="utf-8")
        split = _split_existing(content)
        if split is None:
            problems.append(f"missing generated marker: {path.name}")
            continue
        if split[1] != f"\n{generated}":
            problems.append(f"drifted page: {path.name}")
        if len(content) > PAGE_SIZE_BUDGET:
            print(
                f"glossary: warning: {path.name} exceeds size budget "
                f"({len(content)} > {PAGE_SIZE_BUDGET})"
            )

    if docs_root.exists():
        for stale in sorted(docs_root.glob("*.md")):
            if stale.stem not in pages:
                problems.append(f"stale page: {stale.name}")

    if problems:
        for problem in problems:
            print(f"glossary: {problem}")
        print(
            "glossary: out of sync - run "
            "`python -m talemate.game.engine.nodes.tools glossary --write`"
        )
        return 1

    print(f"glossary: {len(pages)} pages in sync")
    return 0
