<template>

    <v-card class="ma-4">
        <v-card-text class="text-muted text-caption">
            Inspect the prompts and responses generated by the AI.
            <v-btn color="delete" class="ml-2" variant="text" size="small" @click="$emit('clear-prompts')" prepend-icon="mdi-close">Clear</v-btn>
        </v-card-text>
    </v-card>

    <PromptLogItem
        v-for="(prompt, index) in prompts"
        :key="index"
        :prompt="prompt"
        @click="openPromptView(prompt)"
    />

    <DebugToolPromptView ref="promptView" />
</template>
<script>

import DebugToolPromptView from './DebugToolPromptView.vue';
import PromptLogItem from './prompts/PromptLogItem.vue';

export default {
    name: 'DebugToolPromptLog',
    props: {
        prompts: {
            type: Array,
            default: () => [],
        },
    },
    components: {
        DebugToolPromptView,
        PromptLogItem,
    },
    emits: ['clear-prompts'],
    methods: {
        openPromptView(prompt) {
            this.$refs.promptView.open(prompt, this.prompts);
        }
    },
}

</script>
