<template>

    <v-card class="ma-4">
        <v-card-text class="text-muted text-caption">
            Inspect the prompts and responses generated by the AI.
        </v-card-text>
        <v-card-actions class="justify-center">
            <v-btn color="primary" variant="tonal" @click="dumpPromptLog" prepend-icon="mdi-download">Dump to file</v-btn>
            <v-btn color="delete" variant="tonal" @click="$emit('clear-prompts')" prepend-icon="mdi-close">Clear</v-btn>
        </v-card-actions>
    </v-card>

    <PromptLogItem
        v-for="(prompt, index) in prompts"
        :key="index"
        :prompt="prompt"
        @click="openPromptView(prompt)"
    />

    <DebugToolPromptView ref="promptView" />
</template>
<script>

import DebugToolPromptView from './DebugToolPromptView.vue';
import PromptLogItem from './prompts/PromptLogItem.vue';

export default {
    name: 'DebugToolPromptLog',
    props: {
        prompts: {
            type: Array,
            default: () => [],
        },
    },
    components: {
        DebugToolPromptView,
        PromptLogItem,
    },
    inject: ['getWebsocket'],
    emits: ['clear-prompts'],
    methods: {
        openPromptView(prompt) {
            this.$refs.promptView.open(prompt, this.prompts);
        },
        dumpPromptLog() {
            this.getWebsocket().send(JSON.stringify({
                type: 'devtools',
                action: 'dump_prompt_log',
                prompts: this.prompts,
            }));
        },
    },
}

</script>
