name: test-container-build

on:
  workflow_dispatch:
    inputs:
      tag_suffix:
        description: 'Tag suffix for testing (e.g., "-test")'
        required: false
        default: '-test'
        type: string
      build_cuda:
        description: 'Build CUDA variant'
        required: false
        default: true
        type: boolean
      build_cpu:
        description: 'Build CPU variant'
        required: false
        default: true
        type: boolean

permissions:
  contents: read
  packages: write

jobs:
  container-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - cuda: true
            build: ${{ inputs.build_cuda }}
          - cuda: false
            build: ${{ inputs.build_cpu }}
    
    # Only run if the variant is requested
    if: matrix.build == true
    
    steps:
      - uses: actions/checkout@v4

      - name: Set variant name
        run: |
          if [ "${{ matrix.cuda }}" == "true" ]; then
            echo "VARIANT=cuda" >> $GITHUB_ENV
            echo "VARIANT_TAG=-cuda" >> $GITHUB_ENV
          else
            echo "VARIANT=cpu" >> $GITHUB_ENV
            echo "VARIANT_TAG=" >> $GITHUB_ENV
          fi

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: CUDA_AVAILABLE=${{ matrix.cuda }}
          # Tag with test suffix to avoid conflicts with production
          tags: |
            ghcr.io/${{ github.repository }}:latest${{ env.VARIANT_TAG }}${{ inputs.tag_suffix }}
            ghcr.io/${{ github.repository }}:manual-build-${{ github.run_number }}${{ env.VARIANT_TAG }}